morning:
  cron: 34 22 * * *
  args:
  class: ReoccuringInvoice
  description: "Creates all invoices from scheuled invoices"
  queue: :reoccuring_invoice_queue
  
morning:
  cron: 20 21 * * *
  args:
  class: ReminderInvoice
  description: "Creates all invoice payment reminders"
  queue: :reminder_invoice_queue