development:
  bucket: bucketlogo
  access_key_id: AKIAJAPDHBWFPMUHSXCA
  secret_access_key: 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
  s3_host_name: 's3-eu-west-1.amazonaws.com'

test:
  bucket: bucket-test
  access_key_id: xxx
  secret_access_key: xxx
production:
  bucket: bucket-pro
  access_key_id: xxx
  secret_access_key: xxx